### ISSUE TITLE
Flakey Travis CI execution of Reader tests using ThreadPool

### ISSUE THREAD

**Issue by forbearer** [uber/petastorm#104]
A couple examples of such run are:
* Python 2.x: https://travis-ci.com/uber/petastorm/jobs/142290679
    * I've seen the issue happen more regularly with 2.x
* Python 3.x: https://travis-ci.com/uber/petastorm/jobs/142290686

```
petastorm/tests/test_end_to_end.py::test_simple_read[reader_factory1] /home/travis/.travis/job_stages: line 78:  2987 Segmentation fault      (core dumped) pytest -v --ignore=petastorm/tests/test_pytorch_utils.py --ignore=examples/mnist/tests/test_generate_mnist_dataset.py --cov=./
```

**Comment by forbearer** [comment]
@selitvin noted that, despite the ignore, the effect of `import pytorch` in `examples/mnist/tests/conftest.py` must still be bleeding into the main pytest run.

It turns out that that makes sense, because pytest will read the conftest as part of plugin scan.

So, this `-p no:<plugin>` *should* help us!

**Comment by forbearer** [comment]
An alternative approach (which I thought I had tried without success once before, but re-visiting, and manipulating order of the tests as well):  Do `import torch` early as possible in test_generate_mnist_dataset.py, and make sure that's ordered first when running pytest.  This way, I've not introduced a plugin that could bleed `pytorch` module into other tests.

Let's see how this run goes: https://travis-ci.com/uber/petastorm/jobs/142703106

**Comment by selitvin** [comment]
Resolved by adding `import pyarrow` before loading `pytorch` on all code paths.
