### ISSUE TITLE
Split CompressedImageCodec into Png/Jpeg (and may be other) distinct codecs

### ISSUE THREAD

**Issue by selitvin** [uber/petastorm#16]
At the moment the same `CompressedImageCodec` is used for jpeg and png. These two codecs can be configured with different parameters (e.g. jpeg: quality, png: compression ratio). To make these parameter more explicit, it makes sense to split these codecs into two classes.

**Comment by AdamGS** [comment]
Why not add some default params to the init function for the class? I think the rest of the code will be pretty much identical.

**Comment by selitvin** [comment]
Different codecs have parameters that are unique to them. For example, quality-vs-size is something that is applicable only to jpeg and not to png. IMO, having them both behind the same interface (as it is now) makes the API more confusing. At the moment someone may specify a vlaue of quality argument while using a png codec. This combination has not effect but not obvious from the API of the class.
