### ISSUE TITLE
Reduce code complexity of worker_loop function

### ISSUE THREAD

**Issue by selitvin** [uber/petastorm#178]
Currently, flake8 fails on worker_loop being too complex function. Should evaluate if the function can be refactored into smaller pieces.
The following check is currently failing:
```
flake8 . --count --max-complexity=10 --statistics
```
Enable the check as a blocking once the code is refactor and the test passes.

**Comment by cclauss** [comment]
https://github.com/uber/petastorm/blob/master/petastorm/reader_impl/worker_loop.py#L52 is too complex.
