### ISSUE TITLE
Keras supporting

### ISSUE THREAD

**Issue by tjliupeng** [uber/petastorm#192]
Does petastorm support Keras?

**Comment by selitvin** [comment]
Never tried using it from Keras, but since we support `tf.data.Dataset` I believe Keras on Tensorflow should support it. I'll try creating a small example and find out how easy it is.

**Comment by tjliupeng** [comment]
Thanks. Just waiting that example.

**Comment by selitvin** [comment]
Here is an unpolished example: https://github.com/selitvin/petastorm/tree/keras_mnist
Apparently Kares needs the reinitializable_iterator to work properly. We currently support only single shot iterators, but planning to address it in #153 in the near future. Until then, there would be a problem with the way epochs are tracked. 

Please let us know if you were managed to pull it off.
