### ISSUE TITLE
How to change driver for pyarrow.hdfs ?

### ISSUE THREAD

**Issue by manuzhang** [uber/petastorm#193]
Is there an easy way to change the default `libhdfs3` driver for`pyarrow.hdfs` ? We already have Hadoop and `libhdfs` on our classpath.

**Comment by selitvin** [comment]
You can pass `pyarrow_filesystem` value to `Reader` constructor. For example:

```python
with Reader(url, pyarrow_filesystem=pyarrow.hdfs.connect('hdfs:///some/path', driver='libhdfs')) as reader:
  ...
```
