### ISSUE TITLE
Random segmentation faults when using DataLoader

### ISSUE THREAD

**Issue by miguelvr** [uber/petastorm#195]
Hey guys,

I was trying to debug my transform function for petastorm's `DataLoader` when I got a bunch of `Segmentation fault (core dumped)`

The code I was running was simply:

```python
with Reader(dataset_url) as reader:
    for i, row in enumerate(reader):
        print(row.feat_name.shape)
        break
```
However these were not consistent, they just happened sporadically.

Any idea of what it could be?

Best,
Miguel

**Comment by miguelvr** [comment]
It doesn't happen when I use `reader_pool=ProcessPool(10)`

**Comment by selitvin** [comment]
Is there a stack trace that you can provide? 
Can you please run your program like this? It will show which shared libraries are loaded by your program and attach the file?
```bash
LD_DEBUG=files python -c "import sys" 2> /tmp/ld_debug_files.txt
```

Are you using pytorch? Is pytorch loaded at the time of the read (import torch somewhere on the execution path?). Previously we observed some crashes resulted from conflicts between parquet shared library and pytorch. We did not look in details what causes the crash just yet. We found a temporary workaround that worked for us. Try using tcmalloc heap allocator:

```bash
LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4" python myscript.py
```
( you would need tcmalloc for that: `sudo apt install libtcmalloc-minimal4`)

**Comment by miguelvr** [comment]
Yes, I'm using pytorch.

Here you go
[ld_debug_files.txt](https://github.com/uber/petastorm/files/2441426/ld_debug_files.txt)

**Comment by miguelvr** [comment]
@selitvin tcmalloc doesn't solve the problem.

It only seems to run when I use the reader with `ProcessPool` and `pyarrow_serialize=True`

**Comment by selitvin** [comment]
> It only seems to run when 
Can you please clarify: does it crash or runs ok when you use `ProcessPool` and `pyarrow_serialize=True`?
Thanks.

**Comment by selitvin** [comment]
From the `ld_debug_files.txt`
```
$ grep opening ~/Downloads/ld_debug_files.txt  | grep "_C\|parquet"
     26960:	opening file=/home/braincreator/miniconda3/envs/ngpam/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so [0]; direct_opencount=1
     26960:	opening file=/home/braincreator/miniconda3/envs/ngpam/lib/python3.6/site-packages/pyarrow/_parquet.cpython-36m-x86_64-linux-gnu.so [0]; direct_opencount=
```
it appears that you load torch before pyarrow. Apparently, this is a known issue: https://jira.apache.org/jira/browse/ARROW-3346.

I am adding a section to our troubleshoot guide. 

Please try `import pyarrow` as the first import to your main script.

If this does not resolve the issue, please run python with `-X faulthandler` and reply with a call stack.

**Comment by miguelvr** [comment]
> > It only seems to run when
> > Can you please clarify: does it crash or runs ok when you use `ProcessPool` and `pyarrow_serialize=True`?
> > Thanks.

nevermind this, it eventually crashed as well.

> Please try import pyarrow as the first import to your main script.

This seems to solve the issue at first glance. WIll test it further.
Thanks!
