### ISSUE TITLE
Leverage pyarrow predicate filtering

### ISSUE THREAD

**Issue by rgruener** [uber/petastorm#20]
Pyarrow ParquetDataset supports predicate filtering. We should replace our own implementation to utilize theirs https://github.com/apache/arrow/blob/master/python/pyarrow/parquet.py#L789

**Comment by rgruener** [comment]
Update: pyarrow 0.11.0 is scheduled for release sometime in september and will include predicate pushdown

**Comment by danielhaviv** [comment]
I can't find anything online, is there a way to utilize PPD with Petastorm?

**Comment by selitvin** [comment]
We don't support PPD at the moment.

**Comment by bobingm** [comment]
Hi just want to followup here, is there any plan to support this?

**Comment by selitvin** [comment]
The latest Petastorm release (0.9.4) supports passing filters to pyarrow. https://github.com/uber/petastorm/commit/ae95772d3f1d6742ca12d4f56d904a1726326893

**Comment by bobingm** [comment]
I just noticed this change. Thank you for supporting this. Is that possible to support passing filters for all columns, not only partition keys by setting use_legacy_dataset as False in pyarrow.parquet.ParquetDataset[1]?

[1] https://arrow.apache.org/docs/python/generated/pyarrow.parquet.ParquetDataset.html?highlight=parquetdataset

**Comment by selitvin** [comment]
Perhaps we should just forward a dictionary(something like `pa_dataset_args`, that can be used as a `**pa_dataset_args` in a call to ParquetDataset, so we don't have to chase all current and future options pyarrow will implement for ParquetDataset object? 
cc: @tgaddair, @abditag2

**Comment by tgaddair** [comment]
I think making it more flexible for all kwargs sounds good to me, @selitvin.

**Comment by abditag2** [comment]
It does make sense. @bobingm is this something you are willing to make a contribution for? The change must be very similar to my PR. You will only need to accept a kwargs and pass it along to pyarrow.

**Comment by bobingm** [comment]
@abditag2 Sounds good.

**Comment by abditag2** [comment]
Awesome, please ping me when you have it and will review it.

**Comment by selitvin** [comment]
How about we deprecate (newly added :) `filters`) and let users pass the filters directly into the kwargs like structure? That way we won't have two ways of doing the same thing?

**Comment by tgaddair** [comment]
Yes, I absolutely agree that `filters` should be deprecated in favor of `pa_dataset_kwargs` (or whatever it will be called).  For now, I would suggest that the user should not be allowed to specify both, and there should be a `DeprecationWarning` attached to `filters`.

**Comment by abditag2** [comment]
Sounds good to me.

**Comment by bobingm** [comment]
What about `filesystem`, `validate_schema`, `metadata_nthreads`? They are all parameters of `pyarrow.parquet.ParquetDataset`.

**Comment by abditag2** [comment]
I think, we have to keep them for now in order not to break the API.

**Comment by bobingm** [comment]
Yes. I'll add a check if user also provides `filesystem`, `validate_schema`, `metadata_nthreads` in `pa_dataset_args`. If so I will raise a warning message that they will be overwritten.
