### ISSUE TITLE
S3 support

### ISSUE THREAD

**Issue by sytham** [uber/petastorm#210]
Hi, are there plans to add S3 support to the reader? I store my datasets in parquet format on S3, it seems that now I first need to download it locally before I can read it in using petastorm? (Since only file:// and hdfs:// are supported)

**Comment by selitvin** [comment]
I would try using pyarrow.S3FSWrapper (as in https://stackoverflow.com/questions/49085686/pyarrow-s3fs-partition-by-timestamp). `Reader`, takes `pyarrow_filesystem` as a parameter. If you pass `pyarrow.S3FSWrapper` to it, it might just work. I did not try it yet myself.

Another option that we did experiment with is to use s3n to access parquet store using `file://` protocol. That method gave us better throughput than reading the same dataset from an attached EBS storage.

**Comment by sytham** [comment]
Thanks, pyarrow.S3FSWrapper works. The SO post you refer to imports but doesn't actually use S3FSWrapper, but I did the following
```
import s3fs
from pyarrow.filesystem import S3FSWrapper
from petastorm.reader import Reader

dataset_url_without_protocol_prefix = "/something"
fs = s3fs.S3FileSystem()
wrapped_fs = S3FSWrapper(fs)
with Reader(dataset_url_without_protocol_prefix, pyarrow_filesystem=wrapped_fs) as reader:
    <stuff>
```
And (since my dataset was generated without petastorm) I modified `petastorm_generate_metadata.py` to use the same approach.
However, this runs more slowly than when I don't use petastorm and just load the data into a local dataframe and make a Tensorflow dataset from it. But, I imagine this might change when I parameterize the reader for num_epochs etc (at least I hope it doesn't first download everything locally in that case).
In any case, this ticket is resolved.

**Comment by selitvin** [comment]
It depends on the structure of a row: if the row sizes are small, then, indeed, you would suffer from a very poor performance. 

I have this private branch that helps a lot in this case. We are developing it currenly for a similar use case we have internally. It is not ready yet for prime time - will probably take couple of weeks to finish: https://github.com/selitvin/petastorm/tree/zero_copy_scalars. It would provide a zero-copy solution.

Would be happy to hear more about your use case, specifically, the size of your rows, number of columns, what data types are you using.

**Comment by sytham** [comment]
Hi, thanks for now adding S3 support by default! Just to reply to your question about my use case: I have about 1000 columns, all floats (i.e. each row,col position contains a scalar float). Then I have one uint64 column and one np.datetime64[ns] column. Dataset contains about 2 million rows.

Not sure what you consider "small" -- do you think your private branch could help for my case?

**Comment by selitvin** [comment]
Nice! Did not see yet anyone with 1K columns!

Also, FYI, we also landed a https://github.com/uber/petastorm/pull/225 which enables you to read directly from a Parquet store without a need to generate metadata as a pre-step. It might help in a usecase like yours.

**Comment by selitvin** [comment]
Apologies, we still require running `petastorm-generate-metadata.py` manually. Planning to remove the need on `petastorm-generate-metadata.py` soon.
