### ISSUE TITLE
Segmentation fault when use  hdfs as its output_url in  generate_hello_world_dataset.py

### ISSUE THREAD

**Issue by panfengfeng** [uber/petastorm#281]
I try generate_hello_world_dataset.py and use hdfs (local file is OK) as its output_url, but shows "Segmentation fault", any ideas about this problems?

**Comment by selitvin** [comment]
Please see if your segfault is described in https://github.com/uber/petastorm/blob/master/docs/troubleshoot.rst. the solution is to add `import pyarrow` before any other import in the program.

**Comment by panfengfeng** [comment]
Thx, but it does not work. And the problem may result from "libhdfs3" hdfs_driver, since I use "libhdfs", the program is OK

**Comment by selitvin** [comment]
Can you please provide a detailed callstack? Maybe a core dump file?

**Comment by selitvin** [comment]
Unfortunately I was not able to reproduce using our HDFS cluster.

**Comment by jsgoller1** [comment]
I am also running into this issue now, and currently investigating.

**Comment by jsgoller1** [comment]
@panfengfeng Closing again; I was able to resolve this by rolling `pyarrow` back to version `0.12.1`.
