### ISSUE TITLE
generate_hello_world_dataset.py fails with "Passed non-file path"

### ISSUE THREAD

**Issue by Limmen** [uber/petastorm#285]
Hi! Thanks for sharing this library. 

When I am running the example script `generate_hello_world_dataset.py` on our hadoop cluster, the execution fails when it is trying to write out the metadata. E.g:

```bash
Passed non-file path: /Projects/fs_demo/hello_world/dataset2
Traceback (most recent call last):
  File "<stdin>", line 20, in generate_hello_world_dataset
  File "/srv/hops/anaconda/anaconda/envs/python36/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/srv/hops/anaconda/anaconda/envs/python36/lib/python3.6/site-packages/petastorm/etl/dataset_metadata.py", line 97, in materialize_dataset
    validate_schema=False)
  File "/srv/hops/anaconda/anaconda/envs/python36/lib/python3.6/site-packages/pyarrow/parquet.py", line 860, in __init__
    path_or_paths, self.fs, metadata_nthreads=metadata_nthreads)
  File "/srv/hops/anaconda/anaconda/envs/python36/lib/python3.6/site-packages/pyarrow/parquet.py", line 1035, in _make_manifest
    .format(path))
OSError: Passed non-file path: /Projects/fs_demo/hello_world/dataset2
```

The reason for the error is the following:

- When spark writes out the parquet files to the given path, it creates a directory for the path and then writes the partition-files beneath that directory, rather than saving the data to a single file. 

- After the data have been written to the parquet files, the  `petastorm.etl.dataset_metadata.materialize_dataset()` function will save the unischema metadata. When saving the metadata it first creates a pyarrow dataset for the given path, now since the path was written with spark and refers to a **directory** it fails inside pyarrow.parquet.ParquetDataset() at the line `filesystem.isfile(path)` since path is not a file, it is a directory.

It seems that I must be missing some obvious configuration? However I can't find it in the documentation, I took the example code as-is directly from this repository and expected it to work.

Thanks!

**Comment by selitvin** [comment]
Does the example works out-of-the-box, when the dataset is written to a local file system (original value of `output_url='file:///tmp/hello_world_dataset'`)?

Was not able to to reproduce the error:
```
def generate_hello_world_dataset(output_url='hdfs://hdfs_name_node/user/yevgeni/hello_world_dataset_test'):
    ...
```
`generate_hello_world_dataset.py` finished successfully and this is how the result directory looks like:
```
$ hadoop dfs -ls /user/yevgeni/hello_world_dataset_test

Found 4 items
     0 2019-01-15 03:59 /user/yevgeni/hello_world_dataset_test/_SUCCESS
  1256 2019-01-15 03:59 /user/yevgeni/hello_world_dataset_test/_common_metadata
725057 2019-01-15 03:59 /user/yevgeni/hello_world_dataset_test/part-00000-0e8f06b1-43be-49ca-b5d6-64accb2914db-c000.snappy.parquet
725057 2019-01-15 03:59 /user/yevgeni/hello_world_dataset_test/part-00001-0e8f06b1-43be-49ca-b5d6-64accb2914db-c000.snappy.parquet
```

In my case, when stepping through `parquet.py`, I see that the condition at https://github.com/apache/arrow/blob/b65beb625fb14a6b627be667a32c136a79cb5c6f/python/pyarrow/parquet.py#L1015 evaluates to `True`. 

I think I remember that `fs.isdir(path_or_paths)` returns `False` if there are some permission issues accessing the directory (maybe one of the parent directories is not accessible to your user). In this case you would get the misleading error that you actually see. Maybe spark behaves differently (authentication-wise) then the libhdfs3 driver which causes the issue? 

You may try to use `libhdfs` driver which might be handling user authentication more similar to Spark:
```
    fs = FilesystemResolver(dataset_url='hdfs://.../',
                            hdfs_driver='libhdfs').filesystem()
    with materialize_dataset(spark, output_url, HelloWorldSchema, rowgroup_size_mb,
                             pyarrow_filesystem=fs):
```

**Comment by Limmen** [comment]
Thanks, changing to libhdfs fixed that particular error, but got me another error instead.
Im confident this is due to dependency issues that we have with libhdfs3, I'll close this issue.
