### ISSUE TITLE
pyarrow.hdfs.HadoopFileSystem not serializable by Spark

### ISSUE THREAD

**Issue by Limmen** [uber/petastorm#287]
https://github.com/uber/petastorm/blob/e65e327f3bf10ffe95954ceed1a5da89ea0b0ba2/petastorm/etl/dataset_metadata.py#L212

Hi again,

I am using pyspark 2.4.0, and pyarrow 0.11.1 and spark is not able to serialize pyarrow.hdfs.HadoopFileSystem. Have you encountered this issue before? 

I get "HDFS Connection Failed" during the serialization, which is a bit strange. I can open a new filesystem connection inside the spark-mapper with no problem, so there should not be a connection issue but rather a serialization issue. 

Snippet from stacktrace:
`
  File "/srv/hops/hopsdata/tmp/nm-local-dir/usercache/N8YmHUGK9tr5Q9_iz7ZdAb0oU66QXgWDdYzH4tE4wgI/appcache/application_1547648243443_0001/container_e01_1547648243443_0001_01_000002/pyspark.zip/pyspark/serializers.py", line 566, in loads
    return pickle.loads(obj, encoding=encoding)
  File "/srv/hops/anaconda/anaconda/envs/petastorm/lib/python3.6/site-packages/pyarrow/hdfs.py", line 37, in __init__
    self._connect(host, port, user, kerb_ticket, driver, extra_conf)
  File "pyarrow/io-hdfs.pxi", line 105, in pyarrow.lib.HadoopFileSystem._connect
  File "pyarrow/error.pxi", line 83, in pyarrow.lib.check_status
pyarrow.lib.ArrowIOError: HDFS connection failed
`

Thanks
/Kim

**Comment by selitvin** [comment]
I think it is expected for a resource connection not to be serializable. For a file system connection, as in this case, it may include file handles which are not valid outside of the process that `open`ed them.

When we distribute large evaluation task using spark we create Petastorm reader in the function invoked by `map`. From your question, I understand that this solution works for you as well. Would you be able to follow this pattern in your case?

**Comment by Limmen** [comment]
Yes exactly. I can get it working in my fork of petastorm by opening the filesystem connection inside the mapper. However I can not get it working using the upstream version of petastorm. Inside `dataset_metadata.py` there is a spark-mapper that requires the filesystem object to be serialized (function `get_row_group_info(path)` in file `dataset_metadata.py`)

When I try to use `with materialize_dataset(...)` using libhdfs on our cluster I get the serialization issue described above.

**Comment by selitvin** [comment]
You are right. This looks like a bug. Do you pass your own instance of `pyarrow_filesystem` to the `materialize_dataset`? I wonder how come we never saw it with the default libhdfs3 filesystem. We need to fix this. Probably change `pyarrow_filesystem` to `pyarrow_filesystem_factory` and pass the factory into the mapper.

**Comment by Limmen** [comment]
Yes, I pass my own instance of `pyarrow_filesystem`, using libhdfs. The factory approach would be better indeed.

**Comment by selitvin** [comment]
I see that the local filesystem is serialiazable. Probably `libhdfs3` based filesystem is serializable as well.,  while `libhdfs` one is not. That explains that we never ran into it. We'll get it fixed in the next release. Thanks for bringing this up!

**Comment by maver1ck** [comment]
Same problem here... I really didn't want to use libhdfs3 :(

**Comment by selitvin** [comment]
@maver1ck , we are working on a fix for thius and will have a new release within two weeks.

**Comment by jsgoller1** [comment]
@maver1ck / @Limmen  - #310 is now landed so you should be able to pass a filesystem factory method to `materialize_dataset()` (or leave it empty for use with the local filesystem). I'll close this issue for now, but feel free to reopen if the issue resurfaces.
