### ISSUE TITLE
make_batch_reader fails with S3

### ISSUE THREAD

**Issue by GregAru** [uber/petastorm#300]
Looks like `dataset_path` is evaluated differently in `make_reader` and `make_batch_reader`.
In  `make_reader`: `dataset_path = resolver.get_dataset_path()` - executes correctly
In `make_batch_reader`: `dataset_path = resolver.parsed_dataset_url().path` - fails the reader when reading from s3

**Comment by jsgoller1** [comment]
Thanks for reporting this, @GregAru - I will look into it shortly.

**Comment by jsgoller1** [comment]
@GregAru - can you post the code snippet you are trying to run and the error message you are getting? I am able to produce an error for what should be a valid read with `make_batch_reader`, but I want to make sure we're looking at the same issue.

**Comment by jsgoller1** [comment]
@GregAru This should be fixed as of #302 - feel free to reopen if the issue crops up again.
