### ISSUE TITLE
Can't use materialize_dataset with libhdfs

### ISSUE THREAD

**Issue by maver1ck** [uber/petastorm#308]
When using materialize_dataset there is no option to set hdfs_driver.
It's by default set to libhdfs3.

**Comment by selitvin** [comment]
Once we resolve #287 you would be able to pass an instance of a pyarrow filesystem object that uses the libhdfs driver instead of libhdfs3. Should have a release with the fix within two weeks.

**Comment by maver1ck** [comment]
Great.
So setting pyarrow_filesystem to pyarrow.hdfs.connect() ?

**Comment by selitvin** [comment]
Yes. There is a minor issue in `_generate_num_row_groups_per_file` that will try to serialize filesystem object into `get_row_group_info` which will fail when `libhdfs` driver is used. You can hack the fix locally, something like:

```python
    def get_row_group_info(path):
        relative_path = os.path.relpath(path, base_path)
        pq_file = pyarrow.hdfs.connect(...).open(path)
        num_row_groups = pq.read_metadata(pq_file).num_row_groups
        pq_file.close()
        return relative_path, num_row_groups

```
and it should work.

**Comment by jsgoller1** [comment]
@maver1ck - #310 is now landed so you should be able to pass a filesystem factory method to `materialize_dataset()` as described above. I'll close this issue for now, but feel free to reopen if the issue resurfaces.
