### ISSUE TITLE
Make it easier to specify fields in n-gram

### ISSUE THREAD

**Issue by selitvin** [uber/petastorm#332]
`make_reader` takes either a list of UnischemaField objects or regular expressions. Using regular expression in `schema_fields=` argument simplifies user code. `NGram` takes only `UnischemaFields` as a parameter. 

Let's follow the same pattern and allow user to pass a list of regular expressions during `NGram` construction.

**Comment by jpugliesi** [comment]
@selitvin If i'm not mistaken, looks like this can be closed since #365 is complete

**Comment by selitvin** [comment]
Oh, yes, thank you!
