### ISSUE TITLE
Dataset generation from a stream

### ISSUE THREAD

**Issue by GregAru** [uber/petastorm#337]
Not quite an issue but a question.
Is it possible currently to generate a Petastorm Dataset form a streaming data source by using Spark Structured Streaming or any other framework?

**Comment by selitvin** [comment]
That's an interesting question. No, I have not try that. Curious, how would you see petastorm fit into a streaming setup? Do you have an appealing scenario?

**Comment by GregAru** [comment]
I think that it is quite a common scenario when sensor data is ingested in real time via message brokers (Kafka/Kinsesis/...).  Feature extraction and processing is also done in RT via services connected via PUB SUB.  In this architecture it would be simpler to have a Spark Streaming job that incrementally appends partitions to a Petastorm dataset  from the data and metadata as they arrive, instead of orchestrating an additional Spark batch job that needs to list the FS to identify/load the newly arrived files since last execution. 

In my case the data in the message broker includes a reference to an image/audio object stored in S3 as well as extracted features and metadata. I thought to use Spark 2.40's  `writeStream.foreachBatch`  functionality to load the files listed in the batch and write the incoming batches to Parquet with `materialize_dataset`. This way I can avoid listing S3 bucket with 100s millions of images/audio and reduce the overhead of orchestrating batch execution.  Not sure though if `materialize_dataset` is compatible with Spark Structured Streaming...

**Comment by selitvin** [comment]
Is it ok for the number of files to scale with the number of batches, or this is not reasonable?

I have never worked with Spark streaming, so apologies if the following proposal is too naive:

- Each foreachBatch would create a single Petastorm/Parquet dataset into a new directory under your root: e.g. (part_0, part_1, part_2, ) etc... (so we have one `materialize_...` call that covers only one current batch.
- We modify `Reader` class to scan all subdirectories and construct a list of row-groups to load from all directories (not only one, as it is today)
- The rest of the flow remains the same, as the workers load rowgroups from all directories.

As an alternative, we can use proper Parquet partition directory names, and then the entire store like a single valid Parquet dataset and can be accessed from any Parquet compatible tool 
```
part=0/
  ....
part=1/
  ....
```

**Comment by GregAru** [comment]
Thanks for the reply and the information.
I guess I will try it out and see how it goes.
