### ISSUE TITLE
Segmentation fault when using make_batch_reader

### ISSUE THREAD

**Issue by janhaviag** [uber/petastorm#372]
Hi!

 I am trying to read a non-Petastorm parquet file in pytorch but just get the error:

>  Segmentation fault (core dumped)

The code I am using is from examples/hello_world/external_datasets/pytorch_hello_world.py:

`

    with DataLoader(make_batch_reader(file_path_to_my_parquet_file)) as train_loader:
        sample = next(iter(train_loader))
        print("id batch: {0}".format(sample['id']))
`
Any idea why this might be happening?

Thanks,
Janhavi

**Comment by selitvin** [comment]
Good chance it is because of this: https://issues.apache.org/jira/browse/ARROW-5130. We saw it happening with pyarrow 0.13.0. It will be fixed in the next release of pyarrow. For now, I would recommend downgrading to pyarrow 0.12.1 if possible.

**Comment by janhaviag** [comment]
Downgrading the pyarrow version worked. Thanks!
