### ISSUE TITLE
transform_spec does not work with predicate 

### ISSUE THREAD

**Issue by GregAru** [uber/petastorm#401]
I fail to get samples from the Reader when `transform_spec` and `predicate` are provided together in `make_reader` and operate on different fields.

The failure happens because the  transform function is activated with an input that does not include the transformed field. If I add a functionality in the transform function to return the input unchanged if the input fields do not include the transform field - everything works fine, but no transformation is done.

From a short investigation:
With the predicate provided, the transform function is activated when calculating `decoded_predicate_rows` in `PyDictReaderWorker` line 195 and fails since the predicate fields are not the ones I want to transform. Additionally, no transformation is done when calculating the `decoded_other_rows` in line 220.

The only test I have found that includes both `predicate` and `transform_spec` is `test_transform_function_with_predicate_batched` in `test_end_to_end.py`
It passes because both the `predicate` and `transform_spec` operate on the same field.

I am not providing the code, because the issue can be easily reproduced as long as both `transform_spec` and `predicate` are used, with different fields in each.

**Comment by selitvin** [comment]
Thank you for the report. I believe this PR #394 should solve the issue as it moves the transform calculation to run after the predicate. It was hanging there for awhile. I'll make sure it lands today.

**Comment by GregAru** [comment]
The issue was indeed resolved, thank you!
Is there an ETA for release?
