### ISSUE TITLE
Loading a batch size i.e not equal to Row Group Size for PyTorch

### ISSUE THREAD

**Issue by praateekmahajan** [uber/petastorm#405]
Follow up from this issue here https://github.com/uber/petastorm/issues/389

Looks like Tensorflow has utils such as `tf.data.Dataset.unbatch` that allows to get different batch sizes. However for PyTorch its unclear how to get a batch size that is the same as PyTorch [DataLoader](https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader).

Generally for pytorch the following code would suffice :

```
with DataLoader(make_batch_reader(petastorm_dataset_url), batch_size=2) as train_loader:
  for i, data in enumerate(train_loader):
      output = model(data)
      .
      .
      . 
```

However under this setting, could there be an example provided that helps people on the PyTorch boat decide how to use batches as per the Deep learning convention.

**Comment by selitvin** [comment]
Sorry for the late reply - was on a vacation. #411 should solve the issue.
