### ISSUE TITLE
Segmentation fault with materialize_dataset and torch

### ISSUE THREAD

**Issue by mattiasarro** [uber/petastorm#410]
A segmentation fault occurs when you import `materialize_dataset` before `torch`. It happens inside an `ubuntu:16.04` Docker container but not natively on MacOS.

This produces a segfault with `pyarrow==0.13.0` and `pyarrow==0.14.0`, but works with `pyarrow==0.12.1`:

```
from petastorm.etl.dataset_metadata import materialize_dataset
import torch
```

This one works with newer versions of pyarrow:

```
import torch
from petastorm.etl.dataset_metadata import materialize_dataset
```

Initially it looked like this [pyarrow bug](https://issues.apache.org/jira/browse/ARROW-5130), but the workaround for that (placing import pyarrow in the beginning of a program) didn't work, and it shouldn't have affected `pyarrow==0.14.0`.

Closing this issue since there is a workaround already. Just wanted to document this unexpected behaviour.

**Comment by selitvin** [comment]
Thank you for documenting your solution! These kind of binary compatibility issues pop up a lot unfortunately with torch and tensorflow....

**Comment by cupdike** [comment]
I hit this same thing with tensorflow.  My code wasn't even using tensorflow directly. Putting an `import tensorflow` above the petastorm import fixed it:
```
(tensorflow2_p36) ~$ python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from petastorm.tf_utils import make_petastorm_dataset
Segmentation fault (core dumped)

(tensorflow2_p36) :~$ python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
<snip>
>>> from petastorm.tf_utils import make_petastorm_dataset
>>> # GTG
```
Looks like it is a Pyarrow thing:
https://issues.apache.org/jira/browse/ARROW-5130
