### ISSUE TITLE
Nd-array Shape in UnischemaField

### ISSUE THREAD

**Issue by seranotannason** [uber/petastorm#413]
When specifying the shape of an Nd-array in the creation of a UnischemaField object, one is allowed to specify None for the columns that have variable dimensions. Is there anything stopping one from listing None for all the columns (e.g. (None, None, None) for an image)? This may be handy when one is unsure whether a column may have variable dimensions.

**Comment by selitvin** [comment]
There should not be any problem with specifying all dimensions as variable dimensions. You example of `(None, None, None)` should work.

**Comment by selitvin** [comment]
Did the proposed solution work? Can we close this issue?

**Comment by seranotannason** [comment]
Yes, a tuple of just None's works fine. Let's close it
