### ISSUE TITLE
Support for GCS

### ISSUE THREAD

**Issue by dexterfichuk** [uber/petastorm#419]
Would be great to also have support to read data from GCS paths, any plans on updating this. I see ludwig actually already has support for this!

**Comment by megaserg** [comment]
I was able to patch Petastorm code to make it work with GCS. There is `gcsfs` package that's pretty much the same as `s3fs`, except that `pyarrow` provides `S3FSWrapper` for the latter but no `GCSFSWrapper` for the former. So I wrote `GCSFSWrapper` myself and updated the `FilesystemResolver` class.

Actually recent `pyarrow` has native implementation for S3 support: [ARROW-1119](https://issues.apache.org/jira/browse/ARROW-1119).

The Arrow project has put GCS support for later: [ARROW-3717](https://issues.apache.org/jira/browse/ARROW-3717?jql=project%20%3D%20ARROW%20AND%20text%20~%20%22gcs%22%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC).

Does it make sense to add `GCSFSWrapper` to Petastorm? If so, I can open a PR. I understand it would be prudent to have it in `pyarrow` but not sure whether they'll want it.

**Comment by dexterfichuk** [comment]
@megaserg I did the same as you I believe that can be seen on my branch of Petastorm https://github.com/dexterfichuk/petastorm. I had the exact same problem where it felt this should live in a project outside of petastorm, but wasn't sure where.

**Comment by megaserg** [comment]
@dexterfichuk Yeah, I have the same approach. We're contacting Arrow maintainers to see if they want to add the wrapper in `pyarrow`.

**Comment by jeffling** [comment]
What's the verdict on this? would be nice to have this support.

**Comment by selitvin** [comment]
I'd like to get to this but had trouble finding time for this. Seems there are several requests for GCS, so will try to look into it... unless there is someone on this thread that has a good solution that can be made into a PR?
