### ISSUE TITLE
Fetch a specific batch size

### ISSUE THREAD

**Issue by priyankaexp** [uber/petastorm#427]
Tensorflow works better when all the training batches are of the same size. While creating reader via make_batch_reader and converting the dataset to tensorflow dataset via make_petastorm_dataset, there is no way to specify the batch size. The batches retrieved via make_batch_reader is dependent on parquet rowgroups. 

Is there a way to specify a batch size and only retrieve those number of records from S3 in one go?

**Comment by selitvin** [comment]
Do you think rebatching technique described in #359 work in your case?

**Comment by priyankaexp** [comment]
Ohh, it does. Thank you.
