### ISSUE TITLE
results_queue_size defines max number of prefetched row groups?

### ISSUE THREAD

**Issue by GregAru** [uber/petastorm#456]
According to `make_reader` doc:
results_queue_size: Size of the results queue to store prefetched rows

However when debugging I can see that the `_results_queue` in ThreadPool which is affected by this parameter holds full row groups and not individual rows.

Am I missing anything?

**Comment by selitvin** [comment]
That's an error in documentation. It changed awhile ago and the documentation was not updated. I'll update it now. Thanks for pointing it out.
