### ISSUE TITLE
Is there an easy way to transform native Parquet file to Petastorm datasets

### ISSUE THREAD

**Issue by LiuxyEric** [uber/petastorm#463]
Hi, I have a dataset saved as a native parquet file and I used "make_batch_reader" to read it and transform to tensorflow dataset. Everything works fine.

But with the native parquet file format, I can't control the number of batch size and I have to generate lots of parquet partition to reduce the number of training data in a batch in order to fix in the GPU memory which is really inefficient. 

I was wondering is there an easy way to transform native Parquet file to Petastorm datasets?

**Comment by selitvin** [comment]
Would using tensorflow's `unbatch` operation help in your case? See an example here: https://github.com/uber/petastorm/issues/359#issuecomment-483507379

**Comment by LiuxyEric** [comment]
Thanks a lot! It's really helpful!
