### ISSUE TITLE
RuntimeWarning when using pure Python reader with process workers

### ISSUE THREAD

**Issue by filipski** [uber/petastorm#585]
I noticed the following warnings while running benchmarks with pure Pyton reader using process workers (code snippet available in https://github.com/uber/petastorm/issues/584):

```
/home/dfilipsk/miniconda3/envs/petastorm/lib/python3.6/runpy.py:125: RuntimeWarning: 'petastorm.workers_pool.exec_in_new_process' found in sys.modules after import of package 'petastorm.workers_pool', but prior to execution of 'petastorm.workers_pool.exec_in_new_process'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
```

This warning is repeated as many times as the amount of workers in the pool.

**Comment by dmcguire81** [comment]
@selitvin we see this problem, too - any idea what causes this?

**Comment by drelyea-blackberry** [comment]
This is my single greatest annoyance with Petastorm. It forces us to run_training 2> errors.txt just to hide this.

**Comment by amir-abdi** [comment]
It is actually causing our application to crash. Because some modules are not imported when the worker is initialzied, some modules, which we are using withing the worker's workflow, are not available for the sub-process, and the application throws an exception.

How shall we fix that?

**Comment by selitvin** [comment]
I can take a look at this later this week. This is something regarding the way we spawn a process-pool worker and the way unpickling works.

**Comment by carlosfrutos** [comment]
Could have a look at it? I also makes our application crash.

Thank you

**Comment by selitvin** [comment]
> Could have a look at it? I also makes our application crash.
> 
> Thank you

Sure, please take a shot at this.
