### ISSUE TITLE
The boto config used by s3fs is not parameterizeable when instantiated by Petastorm

### ISSUE THREAD

**Issue by dmcguire81** [uber/petastorm#593]
The problem is that their stock configuration uses the [legacy retry mode](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html#available-retry-modes), which is not the recommendation from AWS. Since Petastorm instantiates the `s3fs` client when using either `make_reader` or `make_batch_reader`, there's no opportunity to configure it correctly, and brute-force changes to the `~/.aws/config` file impacts *any* code using `boto3`, even if unrelated, so there is no fine-grained control to the number of retries by use case.

**Comment by selitvin** [comment]
Got it. I assume our idea of parametrizing make_read/make_batch_reader with a file-system instance would solve this. RIght?

**Comment by dmcguire81** [comment]
The merged code solved this, but parameterizing with a `FileSystem` might allow me to work-around the deadlock in the interaction between `pyarrow` and `s3fs`. As mentioned, I'll pull you into that ongoing conversation.
