### ISSUE TITLE
Integration with Apache Hudi

### ISSUE THREAD

**Issue by LuisMoralesAlonso** [uber/petastorm#623]
Hi all,

Is it in the roadmap to do this kind of integration? Being able to use pthon ecosystem directly on top of apache hudi (or other alternatives like iceberg or deltalake) through Petastorm?

Hope your comments,
Luis

**Comment by selitvin** [comment]
We don't have anything special planned for hudi/iceberg/deltalake. The scope of Petastorm is to support direct reading from parquet stores DL frameworks such as pytorch/tensorflow. Not sure about hudi, but if it exposes paths to parquet stores, you should still be able to use Petastorm.
