### ISSUE TITLE
Adding video to README

### ISSUE THREAD

**Issue by crizCraig** [uber/petastorm#635]
Hey @selitvin! Great to see your work here :) This looks like a super useful project! Also love your [presentation](https://www.infoq.com/presentations/petastorm-ml-pipelines/). Seems a shame not to have it on github as well. Very best to you!

**Comment by selitvin** [comment]
Good to hear from you! Thanks for the suggestion - that' a good idea. Added the link to README (#636).

**Comment by selitvin** [comment]
Landed #636

**Comment by crizCraig** [comment]
:boom:
