### ISSUE TITLE
Unable to extract storage_options from URL

### ISSUE THREAD

**Issue by manjuransari** [uber/petastorm#691]
Integration of fsspec  in Petastorm was a great step.

Fsspec support extracting storage_options from input url. In Petastorm, the url format is restricted i.e the option of extracting the storage options from url is blocked.

Petastorm internally converts the input url into required format (get_dataset_path(parsed_url) in fs_utils.py). It would be of great help if we could have mechanism to extract the storage_options from the input url similar to fsspec.

**Comment by selitvin** [comment]
@manjuransari : could you propose a fix PR for this issue?

**Comment by manjuransari** [comment]
@selitvin sure will try to raise PR for the fix.

**Comment by selitvin** [comment]
0.11.2 was released and it includes @manjuransari 's fix. Thanks, Manjur!
