### ISSUE TITLE
pyarrow v.5.0.0 breaks Petastorm Reader

### ISSUE THREAD

**Issue by hgalbraith-bb** [uber/petastorm#707]
`pyarrow` just released their latest version today, which breaks Petastorm. The code that breaks is in `Reader.__init__()` in `reader.py`:

```
        self.dataset = pq.ParquetDataset(dataset_path, filesystem=pyarrow_filesystem,
                                         validate_schema=False, metadata_nthreads=10,
                                         filters=filters)
```

The error message that Petastorm gives is `Can't set attribute`.

**Comment by selitvin** [comment]
Thanks for the report. Looking into this.

**Comment by selitvin** [comment]
We'll cut a release within a couple of days time.

**Comment by hgalbraith-bb** [comment]
Awesome! Thank you! 🎉
