### ISSUE TITLE
How to get length of dataset when using pytorch dataloader API?

### ISSUE THREAD

**Issue by aseembits93** [uber/petastorm#710]
Hi,
Thanks for sharing this repo. It's really useful for my work. I was wondering how I could know the size of a dataset I'm loading using the pytorch API.
```
from petastorm.pytorch import DataLoader
from petastorm import make_reader
with DataLoader(make_reader('file:///tmp/helloworld'), batch_size=64) as train_loader:
    print("length of dataset")
```
Let me Know how I could do it. Thanks in advance!

**Comment by selitvin** [comment]
Currently petastorm has no API for letting you know the number of rows that will be returned. It should be possible to add for the `make_reader` API, but should also be possible to query using standard pyarrow parquet reading tools.

**Comment by v01dXYZ** [comment]
Supposing your dataset was created with `materialize_dataset`, you can directly query the `_metadata` Parquet Metadata File:

```
import pyarrow.parquet as pa

pmd = pa.read_metadata("_metadata")

pmd.num_rows
```

**Comment by aseembits93** [comment]
Thanks @v01dXYZ! I'll close the issue.
