### ISSUE TITLE
_default_delete_dir_handler throws error when using default handler

### ISSUE THREAD

**Issue by manjuransari** [uber/petastorm#716]
We have option to overwrite the method _default_delete_dir_handler. But when we don't overwrite the method, it throws error when used. As we already have fsspec integrated, we can extend fsspec to enable deletion of files.

**Comment by selitvin** [comment]
Not sure I understand. What is the ask here?

**Comment by manjuransari** [comment]
![image](https://user-images.githubusercontent.com/1580666/130182291-240d2161-bf36-4426-b4b5-9e6772999546.png)
We can add our own delete handler. But when we use default handler, as above, the else code fails. We are using fsspec file system but not passing url that is acceptable by fsspec.


For example, we pass dataset_url = 'abfs://synapsemlfs/temp/file.csv'
parsed becomes ParseResult(scheme='abfs', netloc='synapsemlfs', path='/temp/file.csv', params='', query='', fragment='')

When we check fs.exist(parsed.path), we are actually checking for the url = '/temp/file.csv'. This url does not have container/bucket information. The url should be (parsed.netloc + parsed.path) to work flawlessly with fsspec. Also, fsspec support urls with storage_options within url. That particular case is also not handled.

The acceptable code should be as follow:

`def _default_delete_dir_handler(dataset_url):
    resolver = FilesystemResolver(dataset_url)
    fs = resolver.filesystem()
    _dataset_url = strip_protocol(dataset_url)
    if isinstance(fs, LocalFileSystem):
        # pyarrow has a bug: LocalFileSystem.delete() is not implemented.
        # https://issues.apache.org/jira/browse/ARROW-7953
        # We can remove this branch once ARROW-7953 is fixed.
        local_path = _dataset_url 
        if os.path.exists(local_path):
            shutil.rmtree(local_path, ignore_errors=False)
    else:
        if fs.exists(_dataset_url ):
            fs.delete(_dataset_url , recursive=True)`

**Comment by selitvin** [comment]
Would you like to create a PR for this?

**Comment by manjuransari** [comment]
yes, I am working on it. Will raise soon.

**Comment by manjuransari** [comment]
@selitvin is there any plans for a release anytime soon?

**Comment by selitvin** [comment]
Can release tomorrow.

**Comment by selitvin** [comment]
petastorm==0.11.3rc0 is out

**Comment by selitvin** [comment]
0.11.3 released
