### ISSUE TITLE
Use make_batch_reader for petastorm parquet dataset

### ISSUE THREAD

**Issue by PHILO-HE** [uber/petastorm#718]
I noted petastorm has two functions to create dataset reader: `make_reader` & `make_batch_reader`.
According to the comments in source code, 

> (make_reader) Creates an instance of Reader for reading Petastorm datasets

> (make_batch_reader) Creates an instance of Reader for reading batches out of a non-Petastorm Parquet store.

I have some dataset written to HDFS in parquet format with the help of petastorm. In read test on my side, it looks that `make_batch_reader` performed faster than `make_reader` at least in my case, though `make_reader` is the recommended function. 

My question is, for petastorm parquet dataset, can we directly use `make_batch_reader` instead of `make_reader`? Is there any potential issue in doing so? Thanks in advance!

**Comment by selitvin** [comment]
The difference between `make_reader`  and `make_batch_reader` is that the former would do row-by-row processing of deserializing ndarrays from blobs stored in parquet storage. If you don't have any ndarrays `make_batch_reader` is much more lightweight implementation that returns entire row-groups in one go without any processing.

If `make_batch_reader` works in your case, then there is no real downsides, only upsides.

**Comment by PHILO-HE** [comment]
Your answer is very clear to me. Thanks!
