### ISSUE TITLE
got error AssertionError: Must supply a list of namenodes, but HDFS only supports up to 2 namenode URLs when calling the materialize_dataset() in example

### ISSUE THREAD

**Issue by Ereebay** [uber/petastorm#724]
I run the run the mnist example on the cluster, and got error "AssertionError: Must supply a list of namenodes, but HDFS only supports up to 2 namenode URLs" when calling the materialize_dataset(), it seems that hdfs connection failed and the max num of name node server can only be two.

**Comment by selitvin** [comment]
Can you please help me test the PR (#730) on a cluster that has more then two namenodes? I do not have access to one. To install petastorm directly from the branch with the fix try: 
```bash
pip install git+https://github.com/selitvin/petastorm@hadoop3
```

**Comment by selitvin** [comment]
petastorm==0.11.4 with the fix is now available on pypi
