### ISSUE TITLE
PyDictReaderWorker does not support multiple paths datset_paths

### ISSUE THREAD

**Issue by zhangzhenyu13** [uber/petastorm#728]
The Reader class  doest not support multiple paths and throws 
"AttributeError: 'list' object has no attribute 'encode'"
which is due to 160 line in PyDictReaderWorker class file

"cache_key = '{}:{}:{}'.format(hashlib.md5(self._dataset_path.encode('utf-8')).hexdigest(),
                                          piece.path, piece_index)
"

**Comment by selitvin** [comment]
Thank you for the report and sorry for the delayed response. #731 should resolve the issue.

**Comment by selitvin** [comment]
petastorm==0.11.4 with the fix is now available on pypi
