### ISSUE TITLE
reuse dataset materialized by SparkDatasetConverter

### ISSUE THREAD

**Issue by Riser01** [uber/petastorm#735]
Hi team, if we have a large dataset SparkDatasetConverter takes time to first materialize the dataset in the cache directory,

is there a way to save this and reuse it in the future, instead of converting freshly every time 

eg reuse data set created by :

```
penta_train = make_spark_converter(lm_df_train,dtype='float64')
penta_test = make_spark_converter(lm_df_test,dtype='float64')
 
train_size = len(penta_train)
test_size = len(penta_test)
 
print(train_size,test_size)
```

**Comment by selitvin** [comment]
You should be able to use standard pyspark tools to save your dataframe to a parquet store. Then use petastorm to read it in. Notice that make_spark_converter is a relatively recent addition to petastorm that was added to simplify these two steps that in your case should be done manually.
