### ISSUE TITLE
Future Warning importing SparkDatasetConverter.

### ISSUE THREAD

**Issue by kisel4363** [uber/petastorm#775]
The warning:
```
/home/hadoop/.local/lib/python3.7/site-packages/petastorm/spark/spark_dataset_converter.py:28: FutureWarning: pyarrow.LocalFileSystem is deprecated as of 2.0.0, please use pyarrow.fs.LocalFileSystem instead.
  from pyarrow import LocalFileSystem
```
 jumps when the line:
`from petastorm.spark.spark_dataset_converter import SparkDatasetConverter`
is introduced in a pyspark shell.

spark-version: 3.2.1-amzn-0
python-version: 3.7.10
petastorm-version: 0.12.0
pyarrow-version: 9.0.0

**Comment by selitvin** [comment]
This is actually tricky. Appears that we need to support new pyarrow dataset API, which is tricky, to upgrade the filesystem. See #613.

**Comment by kisel4363** [comment]
Thanks a lot @selitvin
