### ISSUE TITLE
How to pass pin_memory argument when using make_torch_dataloader

### ISSUE THREAD

**Issue by s-udhaya** [uber/petastorm#781]
Hi,

I am using petastorm with pytorch. I see [pytorch dataloader ](https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader)supports many arguments such as pin_memory. How would I pass those arguments when I create dataloader using make_torch_dataloader? When I looked at the implementation, it seems that all arguments of pytorch dataloader are not supported in make_torch_dataloader interface. Is there a workaround here?

Thanks

**Comment by selitvin** [comment]
Petastorm does not use pytorch DataLoader class and does not have an equivalent of pin_memory option.

**Comment by s-udhaya** [comment]
I see. I was just confused with the nomenclature :) Thanks for the quick response.
